velodyne_transform_node:
    ros__parameters:
        calibration: 32db.yaml
        model: 32C
        min_range: 0.8
        max_range: 200.0
        view_direction: 0.0
        fixed_frame: ""
        target_frame: ""
        organize_cloud: true
